### ISSUE TITLE
Images / animations on home page are very small on mobile

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/project-website#117]
**Path to the page with the problem (_do not_ include domain name):**

Home page

**Describe the problem:**

Using mobile rendering, the images on the home page are rather small, if not indestiguishable. Especially with the words inside the images, it's hard to see what's going on.

**Screen Shot, if possible**

<img width="377" alt="Screen Shot 2023-04-06 at 3 19 20 PM" src="https://user-images.githubusercontent.com/23109390/230496106-e58ee012-db2f-4ff0-a7cb-ae1ac83ed5f3.png">

**Describe how the site should look?**

Not sure the best design here. Could make the images bigger? Have mobile first images? Drop the images when responding to a mobile layout?

**Comment by jpmcb** [comment]
Although, the image in this chunk looks like it's broken:

<img width="371" alt="Screen Shot 2023-04-06 at 3 21 36 PM" src="https://user-images.githubusercontent.com/23109390/230496319-0af92859-7e33-4ad9-be96-59de9eb63ea5.png">

**Comment by stockholmux** [comment]
These are SVGs, so it makes sense why they are scaling. I think we just need to put in breakpoints to make them full width on narrow screens.
