### ISSUE TITLE
host container paragraph nits

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/project-website#127]
**Path to page with conent (_do not_ include domain name):**

/en/os/1.13.x/concepts/components/

**What content is incorrect?**

This doesn't come across quite right:

```
By default, Bottlerocket has two host containers: the “admin container” and the “control container”. The control container is pre-configured to be able to use the Bottlerocket API; it is on by default and can be accessed by SSM. Provided for system exploration and debugging, the admin container has elevated privileges (disabled by default for security reasons). You can access the admin container either via the control container or through an SSH server running in the admin container.
```

**What should the content say or communicate?**

- There are two host containers that we publish for use with Bottlerocket.
- The control container is on by default.
- The admin container is off by default.
- Any container can be run as a host container.
- Any number of host containers can run.

I think those facts got munged a little bit by saying `By default, Bottlerocket has two host containers: the “admin container” and the “control container”`

**Comment by stockholmux** [comment]
[ this refers to /en/os/1.13.x/concepts/components/ ]

**Comment by webern** [comment]
updated
