### ISSUE TITLE
document software versions for each release

### ISSUE THREAD

**Issue by kdaula** [bottlerocket-os/project-website#14]
Create an initial template followed by a maintainable page to document versions of softwares in each release.

**Comment by stockholmux** [comment]
@mchaker Can you take a look at this?
1. Create a PR  on [DIRECTORY-STRUCTURE.md](https://github.com/bottlerocket-os/project-website/blob/main/DIRECTORY-STRUCTURE.md) that suggests a place for this to live.
2. Confirm that the script above still works / is accurate.
3. Modify that script to add in the correct metadata and format for Hugo.
4. Create a second PR that has that shell script in it as well as documentation on how to use.
