### ISSUE TITLE
Create FAQ for common debugging information

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/project-website#16]
We can consolidate answers to the most commonly asked questions so we have a place to redirect people when they have trouble setting up Bottlerocket. (e.g. Why isn't my node joining the cluster?)

Ancillary to this, we can also document a list system logs/events of interest when something goes wrong.

**Comment by stockholmux** [comment]
Related: #34

**Comment by mchaker** [comment]
FAQ items have been identified. Closing this in lieu of those issues: #98 , #99 , #100 , #101 , #102 , #103
