### ISSUE TITLE
documentation: how do I get back in once I turn off host containers?

### ISSUE THREAD

**Issue by jhaynes** [bottlerocket-os/project-website#17]
If a user disables the control and admin containers, we should have a pod spec or some other way of recovering the instance's connectivity and configurability.

_Originally posted by @jhaynes in https://github.com/bottlerocket-os/bottlerocket/pull/821_

**Comment by stockholmux** [comment]
@mchaker Could you take a look at this? Maybe write it as a FAQ item.

**Comment by arnaldo2792** [comment]
FWIW, turning off the host containers is almost the same as disabling the `sshd` and `ssm-agent` systemd services in other Linux distros.
